# Configuração de build
[build]
  # Pasta onde o seu site (index.html, etc.) está localizado
  publish = "public" 
  # Pasta onde as suas funções de proxy estão localizadas
  functions = "netlify/functions"

# Redirecionamento para o proxy de DADOS da API
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/facilzap-proxy/:splat"
  status = 200
  force = true

# Redirecionamento para o proxy de IMAGENS
# Esta regra é crucial para as imagens funcionarem.
[[redirects]]
  from = "/facilzap-images/*"
  to = "/.netlify/functions/image-proxy?url=:splat"
  status = 200
  force = true

# Configurações das funções
[functions]
  node_bundler = "esbuild"

[functions."*"]
  # Aumenta o tempo máximo de execução para 30 segundos
  timeout = 30
