# Este comando diz à Netlify onde está o seu site principal
# e onde encontrar as funções especiais.
[build]
  publish = "public"
  functions = "netlify/functions"

# Esta regra redireciona as chamadas da API para a nossa função.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true # Garante que esta regra tenha prioridade

# Bloco de configuração para as funções (PARTE ADICIONADA)
[functions]
  # Aumenta o tempo limite padrão de 10s para 30s
  timeout = 30
