[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/facilzap-images/*"
  to = "/.netlify/functions/image-proxy?url=:splat"
  status = 200

[functions]
[functions."*"]
  timeout = 30
  node_bundler = "esbuild"
